### ISSUE TITLE
USER STORY 08: Errors

### ISSUE THREAD

**Issue by lhartley870** [lhartley870/saguaro-bags#10]
Linked Epic: #1 

## Description

As a **site user** I can **see an error response page that is in keeping with the style of the website and can easily navigate back to the home page** so that **I am reassured that I am still navigating within the website and can easily get back to exploring the site**

## Acceptance Criteria
  
* Acceptance Criteria 1: The user sees an error response page that has a similar colour scheme and structure to the rest of the site.
* Acceptance Criteria 2: The user can navigate back to the Home page from the error response page by clicking a button. 
* Acceptance Criteria 3: The response page displays a message appropriate to the error.

## Tasks

- [ ] Create a 404.html and 500.html error page.
- [ ] Style the error pages in line with the rest of the site.
- [ ] Add a button on each error page to take the user back to the home page.
