### ISSUE TITLE
USER STORY 09: Sort the List of Available Bags

### ISSUE THREAD

**Issue by lhartley870** [lhartley870/saguaro-bags#12]
Linked Epic: #11 

## Description

As a **site user** I can **sort the list of available bags** so that **I can easily see the bags I want according to price, rating, style, size, name and colour**

## Acceptance Criteria
  
* Acceptance Criteria 1: The list of all bags for sale on the site can be sorted by price (low to high) and price (high to low).
* Acceptance Criteria 2: The list of all bags for sale on the site can be sorted by rating (high to low) and rating (low to high).
* Acceptance Criteria 3: The list of all bags for sale on the site can be sorted by style (A to Z) and style (Z to A).
* Acceptance Criteria 4: The list of all bags for sale on the site can be sorted by size (S to L) and size (L to S).
* Acceptance Criteria 5: The list of all bags for sale on the site can be sorted by colour (A to Z) and colour (Z to A).
* Acceptance Criteria 6: The list of all bags for sale on the site can be sorted by name (A to Z) and name (Z to A).

## Tasks

- [x] Add sort urls to main_nav.html.
- [x] Add to all_bags view to sort by price (low to high) and price (high to low) - add a final_price annotation so that price can be sorted by either the original price if the bag is not on sale or the discounted price if the bag is on sale.
- [x] Add to all_bags view to sort by rating (high to low) and rating (low to high).
- [x] Add to all_bags view to sort by style/category name (A-Z) and style (Z to A).
- [x] Add to all_bags view to sort by size (smallest to largest) and size (largest to smallest).
- [x] Add to all_bags view to sort by colour name (A-Z) and colour name (Z to A). 
- [x] Add to all_bags view to sort by bag name (A-Z) and bag name (Z to A).
