### ISSUE TITLE
USER STORY 10: Sort a Specific Category of Bag

### ISSUE THREAD

**Issue by lhartley870** [lhartley870/saguaro-bags#13]
Linked Epic: #11 

## Description

As a **site user** I can **sort a specific category of bag** so that **I can easily see the bags in that category according to price, rating, name, style, size and colour**

## Acceptance Criteria
  
* Acceptance Criteria 1: Any group of bags with a particular style can be further sorted by price (low to high and high to low), rating (low to high and high to low), name (A to Z and Z to A), size (S to L and L to S) and colour (A to Z and Z to A).
* Acceptance Criteria 2: Any sale bags can be further sorted by price (low to high and high to low), rating (low to high and high to low), name (A to Z and Z to A), size (S to L and L to S), style (A to Z and Z to A) and colour (A to Z and Z to A).
* Acceptance Criteria 3: Any bags that come with a free charm can be further sorted by price (low to high and high to low), rating (low to high and high to low), name (A to Z and Z to A), size (S to L and L to S), style (A to Z and Z to A) and colour (A to Z and Z to A).

## Tasks

- [x] In bags.html add badge links to show the category/categories the user has selected, a badge link to show if the user has selected to view sale items and a badge link to show if the user has selected to view free charm items.
- [x] Add a select element with options to sort by price (low to high and high to low), size (S-L and L-S), colour (A-Z and Z-A), rating (high to low and low to high), style (A-Z and Z-A) and name (A-Z and Z-A).
- [x] Add the JavaScript for the sort dropdown to work.
