### ISSUE TITLE
USER STORY 11: Searching for a Bag

### ISSUE THREAD

**Issue by lhartley870** [lhartley870/saguaro-bags#14]
Linked Epic: #11 

## Description

As a **site user** I can **search for a bag by name** so that **I can find a specific bag I would like to purchase**

## Acceptance Criteria
  
* Acceptance Criteria 1: Searches entered in the search input box will search the bag names for a matching name and return a list of bags that match.

## Tasks

- [x] Add url link to the all bags page as the search bar form action attribute for both mobile and desktop screens.
- [x] Add to the all_bags view to return an error message if the user doesn't enter any search criteria.
- [x] If the user does enter search criteria filter the bags to those that contain the query (case insensitive).
