### ISSUE TITLE
USER STORY 12: Review Search Results

### ISSUE THREAD

**Issue by lhartley870** [lhartley870/saguaro-bags#15]
Linked Epic: #11 

## Description

As a **site user** I can **easily see what I've searched for and the number of results** so that **I can quickly see if the bag that I want is available**

## Acceptance Criteria
  
* Acceptance Criteria 1: When the user enters a search term, a list of any bags with a name containing that search term are displayed to the user. 
* Acceptance Criteria 2: When a user carries out a search, the number of results is displayed to the user. 
* Acceptance Criteria 3: When a user carries out a search, the search term the user searched is displayed to the user.

## Tasks

- [x] Add a link back to the 'all bags' page if searching/sorting has taken place.
- [x] Add the number of bags being displayed to the user on bags.html.
- [x] Add the search term the user has searched for on bags.html.
