### ISSUE TITLE
USER STORY 31: Privacy Policy

### ISSUE THREAD

**Issue by lhartley870** [lhartley870/saguaro-bags#40]
Linked Epic: #36 

## Description

As a **site user** I can **read the company's privacy policy** so that **I can be confident that the company is complying with GDPR laws**

## Acceptance Criteria
  
* Acceptance Criteria 1: The user can click on a link to the store's privacy policy in the footer. 
* Acceptance Criteria 2: The link takes the user to a page where the privacy policy is displayed.

## Tasks

- [x] Use a privacy policy generator to generate the policy html.
- [x] Create a privacy_policy.html template styled in line with the website's colour scheme.
- [x] Add a view to the home app to display the privacy_policy.html template. 
- [x] Add a url path to the privacy_policy view in the home app.
- [x] Add the link to the privacy policy page to the footer link.
