### ISSUE TITLE
USER STORY 07: Site Navigation

### ISSUE THREAD

**Issue by lhartley870** [lhartley870/saguaro-bags#8]
Linked Epic: #1 

## Description

As a **site user** I can **easily navigate the site** so that **I can find exactly what I want quickly**

## Acceptance Criteria
  
* Acceptance Criteria 1: User has access to a familiar navigation bar at the top of each page of the site.
* Acceptance Criteria 2: Navigation bar shows navigation links in different formats on mobile, medium and desktop screens.
* Acceptance Criteria 3: Navigation bar collapses into a hamburger menu for smaller screens.
* Acceptance Criteria 4: The Navigation bar only displays appropriate navigation links that the user has access to depending on whether or not the user is logged in or is an Admin Site User.
* Acceptance Criteria 5: The Navigation bar displays the user's username when they are logged in.
* Acceptance Criteria 6: The user can navigate back to the Home page by clicking on the 'Home' nav link or the site logo.

## Tasks

- [x] Ensure the site logo and title link back to the Home page.
- [x] Create a hamburger menu navigation for mobile screens.
- [x] Create an 'includes' file for mobile navigation.
- [x] Create an 'includes' file for main navigation on desktop screens.
- [x] Ensure the site title link is visible on medium sized screens with JavaScript.
- [x] Add icons to site navigation to reflect hover and focus states.
- [x] Style spacing and sizing for navbar across different screen widths for responsive design.
